name: Monumenta-Plugins
main: pe.project.Plugin
version: 1.0
commands:
  getServerVersion:
    permission: monumenta.commands.getserverversion
    description: "Gets the current terrain reset version of the server"
    usage: /getServerVersion <version>
  playTimeStats:
    description: "Get the current playtime stats of everyone online"
    usage: /playTimeStats
  chatRange:
    description: Set the default chat range that you can hear people from.
    usage: /chatRange <range>
  isShitty:
    permission: monumenta.commands.isshitty
    description: How sketchy is this person?
    usage: /isShitty <playerName>
  refreshPOITimer:
    permission: monumenta.commands.refreshpoitimer
    description: refresh an internal score from the scoreboard value.
    usage: /refreshpoitimer
  profiling:
    permission: monumenta.commands.profiling
    description: Get Profiling info on the running game.
    usage: /profiling
  setGuildPrefix:
    permission: monumenta.commands.setGuildPrefix
    description: Used to set the prefix tag on a guild
    usage: /setGuildPrefix <team> <prefix> [prefix color] [name color]
  setPlayerName:
    permission: monumenta.commands.setPlayerName
    description: ???
    usage: N/A
  transferScores:
    permission: monumenta.commands.transferScores
    description: Transfers Scoreboard values between one offline player to an online player. This is used to fix players changing names.
    usage: /transferScores <oldPlayerName> <newPlayerName>
  getScore:
    permission: monumenta.commands.getScore
    description: Prints out a specific player's/dummy's passed in scoreboard value.
    usage: /getScore <player/dummy name> <scoreboardName>
  refreshClassEffects:
    permission: monumenta.commands.refreshClassEffects
    description: Refreshes class effects for affected player (either sender or target of /execute)
    usage: /execute @p[stuff] ~ ~ ~ refreshClassEffects
  transferServer:
    permission: monumenta.commands.transferServer
    description: Transfers players with or without inventory between bungee shards.
    usage: /transferserver <server name> [True|False]
  broadcastCommand:
    permission: monumenta.commands.broadcastCommand
    description: Broadcasts a command to run on all Monumenta servers
    usage: /broadcastcommand [command arg1 arg2 ...]
  giveSoulbound:
    permission: monumenta.commands.giveSoulbound
    description: Appends the player's name into lore text on the given item
    usage: /execute @p[stuff] ~ ~ ~ givesoulbound item amount data datatag
  checkEmptyInventory:
    permission: monumenta.commands.checkEmptyInventory
    description: Return success if the player's inventory is empty, fails otherwise
    usage: /execute @p[stuff] ~ ~ ~ checkEmptyInventory
  debugInfo:
    permission: monumenta.commands.debugInfo
    description: Tells the sender information about the target
    usage: /execute @p[stuff] ~ ~ ~ debugInfo
  cleareffects:
    permission: monumenta.commands.cleareffects
    description: Clears all status effects from the player
    usage: /execute @p[stuff] ~ ~ ~ cleareffects
  incrementDaily:
    permission: monumenta.commands.incrementDaily
    description: Increments the servers Daily Version so we can message logging in players and online players when the Daily has reset.
    usage: /incrementDaily
  back:
    permission: monumenta.commands.back
    description: Transfers back to location prior to teleporting. Works multiple times in one session. Saves coordinates to /forward.
    usage: /back [count]
  forward:
    permission: monumenta.commands.forward
    description: Transfers forward to location prior to /back. Works multiple times in one session. Saves coordinates to /back.
    usage: /forward [count]
  questtrigger:
    permission: monumenta.commands.questTrigger
    description: Used by scripted questing system
    usage: What are you doing? You shouldn't be using this!
  minusexp:
    permission: monumenta.commands.minusexp
    description: Subtracts an equivalent amount of levels worth of experience
    usage: /minusexp <levels>
