name: Monumenta-Plugins
main: com.playmonumenta.plugins.Plugin
version: 0.0.1
api-version: 1.13
softdepend: [PlaceholderAPI,Votifier]
commands:
  testnoscore:
    permission: monumenta.command.testnoscore
    description: Succeeds if no entry exists with a particular score on a scoreboard
