name: Monumenta-Plugins
main: com.playmonumenta.plugins.Plugin
version: 0.0.1
api-version: 1.13
softdepend: [PlaceholderAPI,Votifier]
commands:
  transferScores:
    permission: monumenta.command.transferScores
    description: Transfers Scoreboard values between one offline player to an online player. This is used to fix players changing names.
  incrementDaily:
    permission: monumenta.command.incrementDaily
    description: Increments the servers Daily Version so we can message logging in players and online players when the Daily has reset.
  testnoscore:
    permission: monumenta.command.testnoscore
    description: Succeeds if no entry exists with a particular score on a scoreboard
