name: Monumenta_Bossfights
main: com.playmonumenta.bossfights.Plugin
depend: [CommandAPI]
version: dev
api-version: 1.13
commands:
  mobspell:
    description: Used to launch spells
    usage: "usage: /mobspell <spell> [arguments]"
    permission: Mobspell.mobspell
    permission-message: You don't have the permission to use this command.
