name: Monumenta-Plugins
main: com.playmonumenta.plugins.Plugin
version: 3.0.0-5-g617a4b1-dirty
api-version: 1.13
softdepend: [PlaceholderAPI,Votifier]
commands:
  deathMsg:
    permission: monumenta.command.deathmsg
    description: Toggles death messages on and off
  refreshPOITimer:
    permission: monumenta.command.refreshpoitimer
    description: refresh an internal score from the scoreboard value.
  transferScores:
    permission: monumenta.command.transferScores
    description: Transfers Scoreboard values between one offline player to an online player. This is used to fix players changing names.
  refreshClassEffects:
    permission: monumenta.command.refreshClassEffects
    description: Refreshes class effects for affected player (either sender or target of /execute)
  broadcastCommand:
    permission: monumenta.command.broadcastCommand
    description: Broadcasts a command to run on all Monumenta servers
  giveSoulbound:
    permission: monumenta.command.giveSoulbound
    description: Appends the player's name into lore text on the given item
  checkEmptyInventory:
    permission: monumenta.command.checkEmptyInventory
    description: Return success if the player's inventory is empty, fails otherwise
  trackedeffect:
    permission: monumenta.command.trackedeffect
    description: Like /effect but use potion manager to track effect
  incrementDaily:
    permission: monumenta.command.incrementDaily
    description: Increments the servers Daily Version so we can message logging in players and online players when the Daily has reset.
  testnoscore:
    permission: monumenta.command.testnoscore
    description: Succeeds if no entry exists with a particular score on a scoreboard
  updateapartments:
    permission: monumenta.command.updateapartments
    description: Updates player apartment scores
