name: Monumenta-Plugins
main: com.playmonumenta.plugins.Plugin
version: 1.0
softdepend: [PlaceholderAPI,Votifier]
commands:
  playTimeStats:
    description: "Get the current playtime stats of everyone online"
  deathMsg:
    permission: monumenta.command.deathmsg
    description: Toggles death messages on and off
  refreshPOITimer:
    permission: monumenta.command.refreshpoitimer
    description: refresh an internal score from the scoreboard value.
  transferScores:
    permission: monumenta.command.transferScores
    description: Transfers Scoreboard values between one offline player to an online player. This is used to fix players changing names.
  getScore:
    permission: monumenta.command.getScore
    description: Gets a scoreboard value.
  refreshClassEffects:
    permission: monumenta.command.refreshClassEffects
    description: Refreshes class effects for affected player (either sender or target of /execute)
  transferServer:
    permission: monumenta.command.transferServer
    description: Transfers players with or without inventory between bungee shards.
  broadcastCommand:
    permission: monumenta.command.broadcastCommand
    description: Broadcasts a command to run on all Monumenta servers
  giveSoulbound:
    permission: monumenta.command.giveSoulbound
    description: Appends the player's name into lore text on the given item
  hopeifyHeldItem:
    permission: monumenta.command.hopeifyHeldItem
    description: Adds the hope enchant and the player's name to their held item
  gildifyHeldItem:
    permission: monumenta.command.gildifyHeldItem
    description: Adds the Gilded enchant and the player's name to their held item
  checkEmptyInventory:
    permission: monumenta.command.checkEmptyInventory
    description: Return success if the player's inventory is empty, fails otherwise
  debugInfo:
    permission: monumenta.command.debugInfo
    description: Tells the sender information about the target
  cleareffects:
    permission: monumenta.command.cleareffects
    description: Clears all status effects from the player
  trackedeffect:
    permission: monumenta.command.trackedeffect
    description: Like /effect but use potion manager to track effect
  incrementDaily:
    permission: monumenta.command.incrementDaily
    description: Increments the servers Daily Version so we can message logging in players and online players when the Daily has reset.
  back:
    permission: monumenta.command.back
    description: Transfers back to location prior to teleporting. Works multiple times in one session. Saves coordinates to /forward.
  forward:
    permission: monumenta.command.forward
    description: Transfers forward to location prior to /back. Works multiple times in one session. Saves coordinates to /back.
  minusexp:
    permission: monumenta.command.minusexp
    description: Subtracts an equivalent amount of levels worth of experience
  removetags:
    permission: monumenta.command.removetags
    description: Removes all of the target entity's scoreboard tags
  testnoscore:
    permission: monumenta.command.testnoscore
    description: Succeeds if no entry exists with a particular score on a scoreboard
  updateapartments:
    permission: monumenta.command.updateapartments
    description: Updates player apartment scores
