name: Monumenta-Plugins
main: com.playmonumenta.plugins.Plugin
version: 3.3.1-7-gdadc95b-dirty
api-version: 1.13
softdepend: [PlaceholderAPI,Votifier]
commands:
  deathMsg:
    permission: monumenta.command.deathmsg
    description: Toggles death messages on and off
  transferScores:
    permission: monumenta.command.transferScores
    description: Transfers Scoreboard values between one offline player to an online player. This is used to fix players changing names.
  giveSoulbound:
    permission: monumenta.command.giveSoulbound
    description: Appends the player's name into lore text on the given item
  checkEmptyInventory:
    permission: monumenta.command.checkEmptyInventory
    description: Return success if the player's inventory is empty, fails otherwise
  incrementDaily:
    permission: monumenta.command.incrementDaily
    description: Increments the servers Daily Version so we can message logging in players and online players when the Daily has reset.
  testnoscore:
    permission: monumenta.command.testnoscore
    description: Succeeds if no entry exists with a particular score on a scoreboard
  updateapartments:
    permission: monumenta.command.updateapartments
    description: Updates player apartment scores
