name: Monumenta-Plugins
main: com.playmonumenta.plugins.Plugin
version: 1.0
commands:
  playTimeStats:
    description: "Get the current playtime stats of everyone online"
    usage: /playTimeStats
  deathMsg:
    permission: monumenta.commands.deathmsg
    description: Toggles death messages on and off
    usage: /deathmsg <on|off>
  refreshPOITimer:
    permission: monumenta.commands.refreshpoitimer
    description: refresh an internal score from the scoreboard value.
    usage: /refreshpoitimer
  transferScores:
    permission: monumenta.commands.transferScores
    description: Transfers Scoreboard values between one offline player to an online player. This is used to fix players changing names.
    usage: /transferScores <oldPlayerName> <newPlayerName>
  getScore:
    permission: monumenta.commands.getScore
    description: Gets a scoreboard value.
    usage: /getScore <scoreboard> OR /getScore <name> <scoreboard> OR /execute @[...] ~ ~ ~ <scoreboard>
  refreshClassEffects:
    permission: monumenta.commands.refreshClassEffects
    description: Refreshes class effects for affected player (either sender or target of /execute)
    usage: /execute @p[stuff] ~ ~ ~ refreshClassEffects
  transferServer:
    permission: monumenta.commands.transferServer
    description: Transfers players with or without inventory between bungee shards.
    usage: /transferserver <server name> [True|False]
  broadcastCommand:
    permission: monumenta.commands.broadcastCommand
    description: Broadcasts a command to run on all Monumenta servers
    usage: /broadcastcommand [command arg1 arg2 ...]
  giveSoulbound:
    permission: monumenta.commands.giveSoulbound
    description: Appends the player's name into lore text on the given item
    usage: /execute @p[stuff] ~ ~ ~ givesoulbound item amount data datatag
  hopeifyHeldItem:
    permission: monumenta.commands.hopeifyHeldItem
    description: Adds the hope enchant and the player's name to their held item
    usage: /execute @p[stuff] ~ ~ ~ hopeifyHeldItem
  checkEmptyInventory:
    permission: monumenta.commands.checkEmptyInventory
    description: Return success if the player's inventory is empty, fails otherwise
    usage: /execute @p[stuff] ~ ~ ~ checkEmptyInventory
  debugInfo:
    permission: monumenta.commands.debugInfo
    description: Tells the sender information about the target
    usage: /execute @p[stuff] ~ ~ ~ debugInfo
  cleareffects:
    permission: monumenta.commands.cleareffects
    description: Clears all status effects from the player
    usage: /execute @p[stuff] ~ ~ ~ cleareffects
  trackedeffect:
    permission: monumenta.commands.trackedeffect
    description: Like /effect but use potion manager to track effect
    usage: /execute @p[stuff] ~ ~ ~ trackedeffect <PotionEffectType> <seconds> <amplifier>
  incrementDaily:
    permission: monumenta.commands.incrementDaily
    description: Increments the servers Daily Version so we can message logging in players and online players when the Daily has reset.
    usage: /incrementDaily
  back:
    permission: monumenta.commands.back
    description: Transfers back to location prior to teleporting. Works multiple times in one session. Saves coordinates to /forward.
    usage: /back [count]
  forward:
    permission: monumenta.commands.forward
    description: Transfers forward to location prior to /back. Works multiple times in one session. Saves coordinates to /back.
    usage: /forward [count]
  minusexp:
    permission: monumenta.commands.minusexp
    description: Subtracts an equivalent amount of levels worth of experience
    usage: /minusexp <levels>
  removetags:
    permission: monumenta.commands.removetags
    description: Removes all of the target entity's scoreboard tags
    usage: /execute @p[stuff] ~ ~ ~ removetags
  testnoscore:
    permission: monumenta.commands.testnoscore
    description: Succeeds if no entry exists with a particular score on a scoreboard
    usage: /testnoscore <objective> <value>
  updateapartments:
    permission: monumenta.commands.updateapartments
    description: Updates player apartment scores
    usage: /updateapartments
